### ISSUE TITLE
Bug: View button styling does not match the target design

### ISSUE THREAD

**Issue by gylman** [orkhan-m/product-feedback-app-react#2]
![image](https://github.com/user-attachments/assets/1e9927cd-ee88-4a0b-a027-b7f78a03b098)

**Comment by orkhan-m** [comment]
Color should change once there are feedbacks available.

**Comment by gylman** [comment]
It is not about the color, please zoom in, the background color is darker

**Comment by gylman** [comment]
> Color should change once there are feedbacks available.

@orkhan-m  It is not about the color, please zoom in, the background color is darker

**Comment by orkhan-m** [comment]
Button fixed refer to commit: 2ed95fe496077c8733713854f0fd287439f868cd
